[project]
name = "wahrgus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "absl-py>=2.5.0",
    "openai>=3.6.0",
    "openai-codex>=0.147.0",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "tavily-python>=0.8.0",
]
 